### PR TITLE
sepolicy: Define hal_cne_hwservice

### PR DESCRIPTION
**Pull request by johnlaff**
Fix sepolicy errors for files that depend on Hw service manager.

### CODE REVIEW

**Comment by JarlPenguin** [comment]
-1 from me, this isn't required for all ROMs

**Comment by NowDev** [comment]
idk, sepolicy are so fuc***. @rssxda10 decides that.

**Comment by rssxda10** [comment]
LOOOOOOOOOOOOOOOL

**Comment by JarlPenguin** [comment]
It breaks build in ROMs that already have this defined lmao, you should revert this if it works fine already

**Pull request merged**
